### ISSUE TITLE
The kit only support org with all the team for github oauth by default

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/concourse-genesis-kit#21]
The github-oauth subkit only allow us to configure one org with `team all` during `genesis new`. If we would like to configure different orgs with different team permission or use users , we have to do something like this in the env yml file. 
```
instance_groups:
  - name: web
    jobs:
    - name: atc
      properties:
        github_auth:
          authorize:
            - (( replace ))
            - user: xiujiao
```
