### ISSUE TITLE
Kit fails to deploy, unbound variable

### ISSUE THREAD

**Issue by Proplex** [genesis-community/concourse-genesis-kit#25]
**Environment settings:**
CPI: GCP
Genesis build: 7d6531b262
Concourse kit build: 6b563f6
Bash verison: GNU bash, version 4.4.19
OS: Ubuntu 18.04 

**Kit settings:**
Full Concourse
HTTP basic auth
Genesis create self-signed cert
Domain is `ci.testland.com`
1 frontend VM
3 worker VMs

**Kit environment yaml**
```
kit:
  name:    concourse
  version: 5.6.7
  features:
    - (( replace ))
    - full
    - self-signed-cert

params:
  env:   demo-proto
  vault: demo/proto/concourse
  external_domain: ci.testland.com
  num_web_nodes: 1
  worker_count: 3
```

on `genesis deploy demo-proto`:

```
ubuntu@bastion:~/concourse-deployments$ genesis deploy demo-proto
Checking availability of the 'demo-proto' BOSH director...
Preparing to deploy demo-proto to 'demo-proto' BOSH director.

- Fetching cloud config from 'demo-proto'
Downloading cloud config from 'demo-proto' BOSH director...
- Running preflight checks against [demo-proto]:
[demo-proto] running cloud-config and environmental parameter checks...
  cloud-config [OK]
[demo-proto] running manifest viability checks...
./hooks/blueprint: line 30: oauths: unbound variable
Could not determine which YAML files to merge: 'blueprint' hook exited 1
```

It's worth noting that this worked fine on my Mac, which is on `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)`. I think the bug relates to line 24 with `declare -a oauths`. Bash v4 introduced associative arrays with `declare`, not sure if that's why things are mucking up.
